// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Restaurant.Auth.DataAccess;

#nullable disable

namespace Restaurant.Auth.Service.Migrations
{
    [DbContext(typeof(UmContext))]
    [Migration("20240129154009_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Restaurant.Auth.DataAccess.DTO.Auth.RoleDto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Restaurant.Auth.DataAccess.DTO.Auth.UserDto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<DateTime>("RegistrationDT")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registration_dt");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Restaurant.Auth.DataAccess.DTO.Auth.UserToRoleDto", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid?>("UserDtoId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_dto_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_to_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_to_roles_role_id");

                    b.HasIndex("UserDtoId")
                        .HasDatabaseName("ix_user_to_roles_user_dto_id");

                    b.ToTable("user_to_roles", (string)null);
                });

            modelBuilder.Entity("Restaurant.Auth.DataAccess.DTO.Auth.UserToRoleDto", b =>
                {
                    b.HasOne("Restaurant.Auth.DataAccess.DTO.Auth.RoleDto", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_to_roles_roles_role_dto_id");

                    b.HasOne("Restaurant.Auth.DataAccess.DTO.Auth.UserDto", null)
                        .WithMany("Roles")
                        .HasForeignKey("UserDtoId")
                        .HasConstraintName("fk_user_to_roles_users_user_dto_id");

                    b.HasOne("Restaurant.Auth.DataAccess.DTO.Auth.UserDto", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_to_roles_users_user_dto_id1");
                });

            modelBuilder.Entity("Restaurant.Auth.DataAccess.DTO.Auth.UserDto", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
